spring:
  application:
    name: zhou-ai-agent
  profiles:
    active: local
  ai:
    dashscope:
      # 需要替换为真实的 api key
      api-key: local-key
      chat:
        options:
          model: qwen-plus
    vectorstore:
      pgvector:
      index-type: HNSW
      distance-type: COSINE_DISTANCE
      # 如果不确定维度数可以不指定, 不给会默认根据实际维度数指定维度数量
      # 表一旦建好就不能更改维度值了, 最好在之前确认好模型维度
      dimensions: 1536
      max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  datasource:
    # 使用的本地docker创建的镜像, 端口默认5432, 映射为5433
    url: jdbc:postgresql://localhost:5433/zhou_ai_agent
    username: postgres
    password: postgres

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zhou.zhouaiagent.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn